-- CreateTable
CREATE TABLE "Laptop" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "price" INTEGER NOT NULL,
    "sellPrice" INTEGER,
    "description" TEXT NOT NULL,
    "images" TEXT[],
    "brand" TEXT NOT NULL,
    "display_size" DOUBLE PRECISION NOT NULL,
    "display_resolution" TEXT NOT NULL,
    "display_type" TEXT NOT NULL,
    "display_finish" TEXT NOT NULL,
    "display_sensor" BOOLEAN NOT NULL,
    "display_refreshRate" INTEGER NOT NULL,
    "cpu_name" TEXT NOT NULL,
    "cpu_brand" TEXT NOT NULL,
    "cpu_gen" INTEGER NOT NULL,
    "cpu_power" INTEGER NOT NULL,
    "ram_type" TEXT NOT NULL,
    "ram_size" INTEGER NOT NULL,
    "ram_emptySlot" INTEGER NOT NULL,
    "mem_ssd_size" INTEGER,
    "mem_ssd_type" TEXT,
    "mem_ssd_emptySlots" INTEGER NOT NULL,
    "mem_hdd_size" INTEGER,
    "mem_hdd_emptySlots" INTEGER NOT NULL,
    "graphicsCard_discrete_brand" TEXT,
    "graphicsCard_discrete_model" TEXT,
    "graphicsCard_discrete_memory" INTEGER,
    "graphicsCard_integrate_brand" TEXT NOT NULL,
    "graphicsCard_integrate_model" TEXT NOT NULL,
    "camera_mp" DOUBLE PRECISION,
    "camera_ir" BOOLEAN,
    "ports_usbTypeA" INTEGER,
    "ports_usbTypeC" INTEGER,
    "ports_HDMI" INTEGER,
    "ports_DisplayPort" INTEGER,
    "ports_dvd" BOOLEAN NOT NULL,
    "ports_audioJack" INTEGER,
    "ports_rj45" BOOLEAN NOT NULL,
    "keyboard_numBlock" BOOLEAN NOT NULL,
    "keyboard_light" TEXT,
    "network_bluetooth" TEXT NOT NULL,
    "network_wifi" TEXT NOT NULL,
    "network_sim" TEXT,
    "battery_twb" DOUBLE PRECISION,
    "dimensions_w" DOUBLE PRECISION NOT NULL,
    "dimensions_d" DOUBLE PRECISION NOT NULL,
    "dimensions_h" DOUBLE PRECISION NOT NULL,
    "dimensions_kg" DOUBLE PRECISION NOT NULL,
    "originalBox" BOOLEAN NOT NULL,

    CONSTRAINT "Laptop_pkey" PRIMARY KEY ("id")
);
